### ISSUE TITLE
BUG: for dimension in data.findall("dimensions/dimension"): AttributeError: 'NoneType' object has no attribute 'findall

### ISSUE THREAD

**Issue by bengroen** [zypp-io/twinfield#107]
De releases 2.1.0 en 2.1.1 geven onderstaande fout bij de insert/update van dimensies. Dit komt vaak/altijd voor, zodat ik mijn versies heb vastgezet op 2.0.5.

Het lezen van dimensies geeft geen problemen.

```
2023-03-16 08:21:56.807 [INFO ] [root] - Er zijn 6 dimensies met verschillen
2023-03-16 08:21:56.922 [INFO ] [root] - E-mail verzenden: Verschillen dimensies
2023-03-16 08:21:57.352 [INFO ] [root] - Er zijn 6 regels met wijzigingen en 3 regels met nieuwe dimensies.
2023-03-16 08:21:57.433 [INFO ] [root] - 6 dimensies geselecteerd.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/41_selfbilling_zzp/src/verwerken.py", line 31, in <module>
    alleen_verwerken(test=test)
  File "/41_selfbilling_zzp/src/verwerken.py", line 22, in alleen_verwerken
    verwerken_gegevens(stam=stam, df=df, test=test)
  File "/41_selfbilling_zzp/src/main.py", line 29, in verwerken_gegevens
    DimensionSync(
  File "/usr/local/lib/python3.9/site-packages/dimensions/core.py", line 400, in sync
    df_dim_errors, df_dim_correct = self.send_request()
  File "/usr/local/lib/python3.9/site-packages/twinfieldtools/dimensions.py", line 295, in send_request
    df_errors, df_correct = self.parse_response_dimensions(response)
  File "/usr/local/lib/python3.9/site-packages/twinfieldtools/dimensions.py", line 212, in parse_response_dimensions
    for dimension in data.findall("dimensions/dimension"):
AttributeError: 'NoneType' object has no attribute 'findall'
```

De response bevat de volgende tekst. Kan het zijn dat er geen token wordt meegestuurd?

`<soap:Fault><faultcode>soap:Client</faultcode><faultstring>Access denied. Token invalid.</faultstring><faultactor>http://api.accounting2.twinfield.com/webservices/processxml.asmx?wsdl</faultactor><detail><message>Access denied. Token invalid.</message><code>354</code><source>ProcessXmlDocument</source></detail></soap:Fault>`

**Comment by erfannariman** [comment]
@bengroen ter check, is dit nog steeds een issue, dan gaan wij ernaar kijken.
